version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: feedlink-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: feedlink
    ports:
      - "5432:5432"
    volumes:
      - feedlink-pgdata:/var/lib/postgresql/data

volumes:
  feedlink-pgdata:
